### ISSUE TITLE
__main__.py: error: unrecognized arguments: -M

### ISSUE THREAD

**Issue by tarzanwill** [rowanG077/sphinx-multibuild#3]
My code is 
```python3
# You can register a handler that will be called when a symlink
# Can't be created or deleted.
def handle_autobuild_error(input_path, exception):
    pass


# Instantiate multi builder. The last two params are optional.
builder = SphinxMultiBuilder(  # input directories
    ["./components/Excel", "./components/Word"],
    # Temp directory where symlinks are placed.
    "./tmp",
    # Output directory
    "./build",
    # Sphinx arguments, this doesn't include the in-
    # and output directory and filenames argments.
    ["-m", "html", "-c", "./source", "-M"],
    # Specific files to build(optional).
    ["./source/index.rst"],
    # Callback that will be called when symlinking
    # error occurs during autobuilding. (optional)
    handle_autobuild_error)
# build once
builder.build()
```
```python3
class SphinxMultiBuilder(object):
    def __init__(self,
                 input_paths,
                 symlink_path,
                 dest_path,
                 sphinx_args,
                 sphinx_filenames_arg=[],
                 symlink_error_callback=None):

        # Organise arguments passed to sphinx.
        self._sphinx_args = sphinx_args
        try:
            buildIndex = self._sphinx_args.index('-M') + 2
            self._sphinx_args.insert(buildIndex, dest_path)
            self._sphinx_args.insert(buildIndex, symlink_path)
        except ValueError:
            self._sphinx_args.extend([symlink_path, dest_path])
```
I change the '-c' value according to the demo code showed, the sphinx_args like follow: 
```python3
   ["-m", "html", "-c", "./source"],
```
But, when "-M" doesn't regist in the sphinx_args, the program are throwing ValueError. And if take the sphinx_args like this
```python3
 ["-m", "html", "-c", "./source", "-M"],
```
then the program throws `__main__.py: error: unrecognized arguments: -M`,  it looks like a confilct here.

So, how the SphinxMultiBuilder.build run correctly ?

**Comment by rowanG077** [comment]
Where does it throw `ValueError`, the code simply catches a `ValueError`?

The error `__main__.py: error: unrecognized arguments: -M` is coming from sphinx when the multibuilder calls it. It's not an error in the multibuilder. Beside the `-M` argument like that is completely wrong. You should read up on sphinx documentation.

**Comment by tarzanwill** [comment]
Well, according to the demo code, I can't run this. And I've pip installed the pacakge, but no command found. Probobaly, I will  figure out it or not. 
Thanks your reply :)

**Comment by rowanG077** [comment]
What do you mean according to the demo code you can't run this. What happens if you don't add the `-M` flag? This should work. If not then please post the issue you are having!
