### ISSUE TITLE
Python 3 Support on Windows

### ISSUE THREAD

**Issue by kolrami** [rowanG077/sphinx-multibuild#4]
Hi @rowanG077, not sure if this is still maintained but I tried it on windows with python 3.6 but unfortunately unicode() is not existing any longer but we should just use str(). Is there a chance to get this fixed?

**Comment by rowanG077** [comment]
Yeah it's still maintained. This is indeed an oversight. I will fix it asap.

**Comment by rowanG077** [comment]
I think it should be fixed. I unfortunately don't have windows so I couldn't test it. I have created a new release on pypi. Please check if the new version fixes the issue!

**Comment by kolrami** [comment]
Cool, thank you very much for the quick fix. It runs now but unfortunately the symlink did not work for me. I believe it is because you need to enable the developer mode for creating them in unprivileged mode.

**Comment by rowanG077** [comment]
Yeah that's an unfortunate limitation of windows. You either have to run python as admin or have to enable developer mode. Nothing I can really do about that...
