### ISSUE TITLE
When two doc projects have the same filename, only the last one is handled

### ISSUE THREAD

**Issue by flickerfly** [rowanG077/sphinx-multibuild#5]
When I have multiple -i options handed that each have an index.rst, the resulting index.html will only be the last project directory managed.

This means I miss out on a good bit of documentation due to a lot of similarity between the projects I'm trying to build all at once.

**Comment by rowanG077** [comment]
I'm not sure how this should work. Any exact filename clash will result in this.

The only way out of this is to create, or allow a user to specify, a "top-level" index that must not be in the input folders.

What is the behavior you expect?

**Comment by flickerfly** [comment]
I was expecting each project to have its own namespace or something like that so the project would have their own space and then a central index at the top-level of the output that would link to the related projects.

**Comment by rowanG077** [comment]
Sphinx doesn't support namespaces.

What you can do to achieve what you want is to give one project an index.rst for both projects and the put the rest of both projects in a unique sub-folder.

**Comment by rowanG077** [comment]
Is my suggesting working for you @flickerfly?

**Comment by flickerfly** [comment]
No it isn't, but I was able to just rewrite the Makefile and use
intersphinx to address my need. The central Makefile now uses recursive
make commands into the other projects.
