### ISSUE TITLE
How to give conf.py for each repo as parameters

### ISSUE THREAD

**Issue by leicao-me** [rowanG077/sphinx-multibuild#6]
Hi @rowanG077 ,

Thank you very much for building this awesome project. 

I have a question about the conf.py file. I know by using multiple '-i' I can specify multiple repos, but how to specify the conf.py file location for each repo using '-c'?

Thank you.

**Comment by rowanG077** [comment]
Unfortunately it's not possible to have multiple `conf.py` files. The goal of this project is to be able to merge different `rst` sources into a single Sphinx project. 

If you want to be able to have two separate Sphinx project being seen as "one" then I think [intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) is what you are looking for.

**Comment by leicao-me** [comment]
I see. Thank you very much. I’ll take a look.
