### ISSUE TITLE
Conflict between folders with same name in two projects

### ISSUE THREAD

**Issue by chausner-audeering** [rowanG077/sphinx-multibuild#7]
I am using sphinx-multibuild to build two Sphinx projects that both have an `images` directory:
```
Project A:
images/a.png

Project B:
images/a.png
images/b.png
```

Image `a.png` is the same between both projects, image `b.png` is only present in project B. When I build, I get the following warning and the image is missing in the HTML output:
```
.../index.rst:: WARNING: image file not readable: images/b.png
```

I can workaround this issue by giving the folder in Project B a unique name:
```
Project B:
images2/a.png
images2/b.png
```

Is this a known issue/limitation of sphinx-multibuild? I can see why the same filename could lead to conflicts (a.png) but the error actually does not occur with a.png but with b.png. I would have expected sphinx-multibuild to merge the two directories (and ideally print a warning about a.png being present in two projects).

Is ensuring unique folder names the recommended solution or are there better workarounds?

**Comment by rowanG077** [comment]
Yes this is a known limitation. Like described in the README sphinx-multibuild only symlinks two directories together. It's not in any way designed to do any conflict resolution between the two. The easiest way to handle this is to just have two completely different sub-directories for each project you want to combine using sphinx-multibuild.

**Comment by chausner-audeering** [comment]
Thanks for the quick reply! Okay, good to know. It's not a nice solution and would certainly not scale to bigger projects but it will work for us for now.
